"""Contrats de stockage (protocoles structurels)."""

from __future__ import annotations

from typing import Protocol

from tracker.binder_models import BinderConfigPayload, BinderPlacementsPayload
from tracker.models import CardList, CollectionProgress, TrainerContactBook


class ProgressRepository(Protocol):
    def load(self) -> CollectionProgress: ...
    def save(self, data: CollectionProgress) -> None: ...


class BinderConfigRepository(Protocol):
    def load(self) -> BinderConfigPayload: ...
    def save(self, data: BinderConfigPayload) -> None: ...


class BinderPlacementsRepository(Protocol):
    def load(self) -> BinderPlacementsPayload: ...
    def save(self, data: BinderPlacementsPayload) -> None: ...


class CardRepository(Protocol):
    def load(self) -> CardList: ...
    def save(self, data: CardList) -> None: ...


class TrainerContactRepository(Protocol):
    def load(self) -> TrainerContactBook: ...
    def save(self, data: TrainerContactBook) -> None: ...
